name: Matrix CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and Test
      run: |
        g++ -o test_app src/matrix.cpp src/test.cpp
        ./test_app
