name: Matrix Calculator CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ doxygen graphviz valgrind
        
    - name: Build application
      run: |
        g++ -o matrix_app src/matrix.cpp src/main.cpp
        g++ -o test_app src/matrix.cpp src/test.cpp
        
    - name: Run tests
      run: ./test_app
      
    - name: Check memory leaks
      run: |
        valgrind --leak-check=full --error-exitcode=1 ./test_app